apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./crds
- gateways.yaml
- httproutes.yaml
- refgrant.yaml
#- tcp-udp-routes.yaml

patchesJson6902:
  - target:
      group: ""
      version: v1
      kind: Service
      name: cilium-gateway-tls-gateway
    path: cilium-patches.yaml
