{
 "title": "NAS Storage",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "NFS Raid", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Used Percent",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"disk\" )\n|> filter(fn: (r) => r.device == \"md0\" )\n|> filter(fn: (r) => r._field == \"used_percent\" )"
    }
   ]
  },
  {
   "title": "Total capacity",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dectbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"disk\" )\n|> filter(fn: (r) => r.device == \"md0\" )\n|> filter(fn: (r) => r._field == \"total\" )\n|> last()  \n|> map(fn: (r) => ({r with _value: float(v: r._value) / 1024.0 / 1024.0 / 1024.0 / 1024.0}))"
    }
   ]
  },
  {
   "title": "Used capacity",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dectbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"disk\" )\n|> filter(fn: (r) => r.device == \"md0\" )\n|> filter(fn: (r) => r._field == \"used\" )\n|> last()  \n|> map(fn: (r) => ({r with _value: float(v: r._value) / 1024.0 / 1024.0 / 1024.0 / 1024.0}))"
    }
   ]
  },
  {
   "title": "Free capacity",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dectbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"disk\" )\n|> filter(fn: (r) => r.device == \"md0\" )\n|> filter(fn: (r) => r._field == \"free\" )\n|> last()  \n|> map(fn: (r) => ({r with _value: float(v: r._value) / 1024.0 / 1024.0 / 1024.0 / 1024.0}))"
    }
   ]
  },
  { "title": "Backup disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Used Percent",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"disk\" )\n|> filter(fn: (r) => r.device == \"sdc\" )\n|> filter(fn: (r) => r._field == \"used_percent\" )"
    }
   ]
  },
  {
   "title": "Total capacity",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dectbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"disk\" )\n|> filter(fn: (r) => r.device == \"sdc\" )\n|> filter(fn: (r) => r._field == \"total\" )\n|> last()  \n|> map(fn: (r) => ({r with _value: float(v: r._value) / 1024.0 / 1024.0 / 1024.0 / 1024.0}))"
    }
   ]
  },
  {
   "title": "Used capacity",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dectbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"disk\" )\n|> filter(fn: (r) => r.device == \"sdc\" )\n|> filter(fn: (r) => r._field == \"used\" )\n|> last()  \n|> map(fn: (r) => ({r with _value: float(v: r._value) / 1024.0 / 1024.0 / 1024.0 / 1024.0}))"
    }
   ]
  },
  {
   "title": "Free capacity",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dectbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"disk\" )\n|> filter(fn: (r) => r.device == \"sdc\" )\n|> filter(fn: (r) => r._field == \"free\" )\n|> last()  \n|> map(fn: (r) => ({r with _value: float(v: r._value) / 1024.0 / 1024.0 / 1024.0 / 1024.0}))"
    }
   ]
  }
 ]
}