apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ditc-cert
  namespace: pki
spec:
  secretName: ditc-certificate-secret
  issuerRef:
    name: my-ca-issuer
    kind: Issuer
    namespace: pki
  commonName: ditc.lcldns
  dnsNames:
    - owncloud.ditc.lcldns
    - grafana.ditc.lcldns