apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: owncloud-helm-charts
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - https://owncloud-docker.github.io/helm-charts