---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb-operator
  namespace: argocd
spec:
  project: mariadb-helm-charts
  source:
    chart: mariadb-operator
    repoURL: https://mariadb-operator.github.io/mariadb-operator
    targetRevision: 0.27.0
    helm:
      releaseName: mariadb-operator
      values: |-
        metrics:
          enabled: true
        webhook:
          certificate:
            certManager: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: data-storage
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      selfHeal: true
      prune: true