apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mariadb-helm-charts
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - https://mariadb-operator.github.io/mariadb-operator