apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prometheus-community-helm-charts
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - https://prometheus-community.github.io/helm-charts