apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: upgrades
  namespace: argocd
spec:
  destination:
    namespace: 'kube-system'
    server: 'https://kubernetes.default.svc'
  source:
    path: upgrades
    repoURL: 'replace-me'
    targetRevision: main
  project: local-k8s
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
