apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
spec:
  project: pihole-helm-charts
  source:
    chart: pihole
    repoURL: https://mojo2600.github.io/pihole-kubernetes/
    targetRevision: 2.22.0
    helm:
      releaseName: pihole
      values: |-
        replicaCount: 2
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
               nodeSelectorTerms:
               - matchExpressions:
                 - key: kubernetes.io/hostname
                   operator: In
                   values:
                   - ditc-k8s-master
                   - ditc-k8s-worker2
        serviceDns:
          type: LoadBalancer
          annotations:
            metallb.universe.tf/loadBalancerIPs: 10.54.42.153
            metallb.universe.tf/allow-shared-ip: pihole-dns-tcp,pihole-dns-udp
        dnsmasq:
          customDnsEntries:
            - address=/owncloud.ditc.lcldns/10.54.42.150
            - address=/grafana.ditc.lcldns/10.54.42.150
            - address=/argocd.ditc.lcldns/10.54.42.150
            - address=/hubble.ditc.lcldns/10.54.42.150
            - address=/vault.ditc.lcldns/10.54.42.150
  destination:
    server: "https://kubernetes.default.svc"
    namespace: connectivity
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
