#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: tailscale-tls-gateway-proxy
#  namespace: connectivity
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      name: tailscale-tls-gateway-proxy
#  template:
#    metadata:
#      labels:
#        name: tailscale-tls-gateway-proxy
#    spec:
#      serviceAccountName: "tailscale"
#      initContainers:
#        # In order to run as a proxy we need to enable IP Forwarding inside
#        # the container. The `net.ipv4.ip_forward` sysctl is not allowlisted
#        # in Kubelet by default.
#        - name: sysctler
#          image: busybox
#          securityContext:
#            privileged: true
#          command: ["/bin/sh"]
#          args:
#            - -c
#            - sysctl -w net.ipv4.ip_forward=1 net.ipv6.conf.all.forwarding=1
#          resources:
#            requests:
#              cpu: 1m
#              memory: 1Mi
#      containers:
#        - name: tailscale
#          imagePullPolicy: Always
#          image: "ghcr.io/tailscale/tailscale:v1.48.1"
#          env:
#            # Store the state in a k8s secret
#            - name: TS_KUBE_SECRET
#              value: "tailscale-tls-gateway-proxy"
#            - name: TS_USERSPACE
#              value: "false"
#            - name: TS_HOSTNAME
#              value: "tailscale-tls-gateway-proxy"
#            - name: TS_AUTHKEY
#              valueFrom:
#                secretKeyRef:
#                  name: tailscale-auth
#                  key: TS_AUTHKEY
#                  optional: true
#            - name: TS_DEST_IP
#              value: "10.54.42.150" # cilium-gateway-tls-gateway svc clusterip
#            - name: TS_AUTH_ONCE
#              value: "true"
#          securityContext:
#            capabilities:
#              add:
#                - NET_ADMIN

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale-pihole-tcp-proxy
  namespace: connectivity
spec:
  replicas: 1
  selector:
    matchLabels:
      name: tailscale-pihole-tcp-proxy
  template:
    metadata:
      labels:
        name: tailscale-pihole-tcp-proxy
    spec:
      serviceAccountName: "tailscale"
      initContainers:
        # In order to run as a proxy we need to enable IP Forwarding inside
        # the container. The `net.ipv4.ip_forward` sysctl is not allowlisted
        # in Kubelet by default.
        - name: sysctler
          image: busybox
          securityContext:
            privileged: true
          command: ["/bin/sh"]
          args:
            - -c
            - sysctl -w net.ipv4.ip_forward=1 net.ipv6.conf.all.forwarding=0
          resources:
            requests:
              cpu: 1m
              memory: 1Mi
      containers:
        - name: tailscale
          imagePullPolicy: Always
          image: "ghcr.io/tailscale/tailscale:v1.58.2"
          env:
            # Store the state in a k8s secret
            - name: TS_KUBE_SECRET
              value: "tailscale-pihole-tcp-proxy"
            - name: TS_USERSPACE
              value: "false"
            - name: TS_ACCESS_DNS
              value: "false"
            - name: TS_HOSTNAME
              value: "tailscale-pihole-tcp-proxy"
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: tailscale-auth
                  key: TS_AUTHKEY
                  optional: true
            - name: TS_DEST_IP
              value: "10.43.100.131" # pihole-dns-tcp svc clusterip
            - name: TS_AUTH_ONCE
              value: "true"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale-pihole-udp-proxy
  namespace: connectivity
spec:
  replicas: 1
  selector:
    matchLabels:
      name: tailscale-pihole-udp-proxy
  template:
    metadata:
      labels:
        name: tailscale-pihole-udp-proxy
    spec:
      serviceAccountName: "tailscale"
      initContainers:
        # In order to run as a proxy we need to enable IP Forwarding inside
        # the container. The `net.ipv4.ip_forward` sysctl is not allowlisted
        # in Kubelet by default.
        - name: sysctler
          image: busybox
          securityContext:
            privileged: true
          command: ["/bin/sh"]
          args:
            - -c
            - sysctl -w net.ipv4.ip_forward=1 net.ipv6.conf.all.forwarding=0
          resources:
            requests:
              cpu: 1m
              memory: 1Mi
      containers:
        - name: tailscale
          imagePullPolicy: Always
          image: "ghcr.io/tailscale/tailscale:v1.58.2"
          env:
            # Store the state in a k8s secret
            - name: TS_KUBE_SECRET
              value: "tailscale-pihole-udp-proxy"
            - name: TS_USERSPACE
              value: "false"
            - name: TS_ACCESS_DNS
              value: "false"
            - name: TS_HOSTNAME
              value: "tailscale-pihole-udp-proxy"
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: tailscale-auth
                  key: TS_AUTHKEY
                  optional: true
            - name: TS_DEST_IP
              value: "10.43.148.156" # pihole-dns-udp svc clusterip
            - name: TS_AUTH_ONCE
              value: "true"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
