apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: load-balancer
  namespace: connectivity
spec:
  addresses:
    - 10.54.42.150-10.54.42.254

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advertisement
  namespace: connectivity
spec:
  ipAddressPools:
    - load-balancer
