apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  project: bitnami-helm-charts
  source:
    chart: redis
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 18.19.2
    helm:
      releaseName: redis
      values: |-
        auth:
          password: "12345"
        replica:
          replicaCount: 2
        metrics:
          enabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: data-storage
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
