apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: vault-helm-charts
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - https://helm.releases.hashicorp.com