apiVersion: mariadb.mmontes.io/v1alpha1
kind: Grant
metadata:
  name: owncloud
  namespace: data-storage
spec:
  mariaDbRef:
    name: mariadb
  privileges:
    - "SELECT"
    - "INSERT"
    - "UPDATE"
    - "DELETE"
  database: "*"
  table: "*"
  username: owncloud
  grantOption: true
  host: "%"