apiVersion: v1
kind: Secret
metadata:
  name: bitnami-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: bitnami-repo
  url: registry-1.docker.io/bitnamicharts
  enableOCI: "true"
  type: helm